- ssf/files/tofs_php-formula/pre-commit_semantic-release.sh
- ssf/files/tofs_php-formula/release.config.js
- ssf/files/tofs_ssf-formula/pre-commit_semantic-release.sh
* References:
- https://github.com/saltstack-formulas/php-formula/pull/175#issuecomment-517492613
- https://github.com/saltstack-formulas/php-formula/pull/185#issuecomment-517603898
* Ensure this only runs until `v1.0.0` (done in the script)
---
The second commit is a fix for f9b74e3, which was missing the `v` prefix, found while working on the first commit.
CC: @n-rodriguez @sticky-note.
> feat(php): update deprecation version number in `semantic-release` run

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/influxdb-formula/pull/24
> feat(formula): add `openssh-formula`

- ssf/files/tofs_libvirt-formula/inspec/README.md
* Supposed to be included in #24
* Was used when preparing https://github.com/saltstack-formulas/libvirt-formula/pull/58
> fix(libvirt): add missed custom inspec `README` template

- ssf/defaults.yaml
- ssf/files/default/.travis.yml
- ssf/files/default/kitchen.yml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/template-formula/pull/163
* https://docs.travis-ci.com/user/reference/bionic/
* https://docs.travis-ci.com/user/reference/linux
* https://stackoverflow.com/a/47880689
> feat: use `dist: bionic` & apply `opensuse-leap-15` SCP error workaround

- ssf/defaults.yaml
- ssf/files/default/.travis.yml
- ssf/formulas.yaml
With this PR, `salt-formula` will also be "fully-managed" by this formula (that is, in as much as formulas are managed).
> feat(salt): add remaining sections (Kitchen, InSpec & Travis)

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/lvm-formula/pull/15
> feat(formula): add `lvm-formula`

- ssf/config/formulas.sls
- ssf/defaults.yaml
- ssf/files/default/.cirrus.yml
- ssf/files/default/.travis.yml
- ssf/files/default/kitchen.yml
- ssf/formulas.yaml
- ssf/libcimatrix.jinja
Split out from #45 so that it can be merged now, while the upstream PR is evaluated.
---
Had a number of steps to be done before this could be realised.
```
fix(libcimatrix): convert any underscores to hyphens for suite names
```
* `vault-formula` uses underscores, which translate into hyphens when checking with `kitchen list -b`.
```
feat: allow explicit specification of empty suites (i.e. `name: ''`)
* Empty suites are used to run all suites during the Travis run
* Before this, these were handled implicitly when they were set
- E.g. `vault-formula` had 3 suites defined but all of them running
for each instance
```
* This was the main body of work required to implement this functionality.
* Most of the diff is actually whitespace changes due to indenting one level further, due to the …
> feat(vault): prepare for splitting suites for `vault-formula`

- ssf/defaults.yaml
- ssf/files/default/kitchen.yml
* The current pre-salted `opensuse` images are using `mirror.23media.com`
- https://github.com/netmanagers/salt-image-builder/blob/d6e57f6b22570530a627c89a94fed02754a3197d/scripts/prepare.sh#L99
- This has been proving to be unreliable in recent days, causing failed builds
* Preparing new pre-salted images would pull in `2019.2.1`, which is a no-go
- https://github.com/netmanagers/salt-image-builder/issues/7
- https://github.com/saltstack/salt/issues/54765
* This workaround is to use bootstrapped images in the interim
---
To do this effectively, had to prepare with another commit first:
```
refactor(kitchen): use macros for each section under `driver`
```
* Separated the logic in the `kitchen.yml` template, so that this workaround could be applied a bit more cleanly.
---
Final point, when …
> feat(kitchen): use bootstrapped `opensuse` images until `2019.2.2`

- ssf/defaults.yaml
- ssf/files/default/kitchen.yml
* Completes #52
* Found when working on https://github.com/saltstack-formulas/vault-formula/pull/47
- Wasn't necessary while testing on the `template-formula`
* List of packages taken from:
- https://github.com/netmanagers/salt-image-builder/blob/d6e57f6b22570530a627c89a94fed02754a3197d/scripts/prepare.sh
- Removed duplicate `net-tools`
- Removed extraneous `udev` (installed already during initial provisioning)
> fix(kitchen): install required packages to bootstrapped `opensuse`

- ssf/defaults.yaml
- ssf/files/default/.github/ISSUE_TEMPLATE/bug_report.md
- ssf/files/default/.github/ISSUE_TEMPLATE/feature_request.md
* https://github.com/saltstack-formulas/template-formula/pull/174
> feat(issues): update templates for all `semrel_formulas`

- ssf/defaults.yaml
- ssf/files/default/.yamllint
> feat(yamllint): update ignored paths and add `octal-values`

- ssf/defaults.yaml
- ssf/formulas.yaml
The plan here is to clear the formulas where it is easy to fix this, e.g.
* `salt-formula`: Everything fixed automatically with `rubocop --safe-auto-correct`.
> feat(formulas): merge `rubocop` linter into main `lint` job

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/iscsi-formula/pull/23
> feat(formula): add `iscsi-formula`

- ssf/defaults.yaml
- ssf/files/default/.travis.yml
* https://github.com/warpnet/salt-lint/pull/49
* Removes part of the customisations of c3acbd103e62b4a5213e730f369c93084eda4140
---
Completed in https://github.com/saltstack-formulas/ufw-formula/commit/698dad815f4c74cc311300ec053a1f2c01fb6fbb.
> feat(ufw): remove `PyYAML` requirement for `salt-lint` in `.travis.yml`

- ssf/defaults.yaml
- ssf/files/default/.salt-lint
- ssf/files/tofs_apache-formula/.salt-lint
- ssf/files/tofs_docker-formula/.salt-lint
- ssf/files/tofs_mysql-formula/.salt-lint
- ssf/files/tofs_openssh-formula/.salt-lint
- ssf/files/tofs_php-formula/.salt-lint
- ssf/files/tofs_postfix-formula/.salt-lint
- ssf/files/tofs_zabbix-formula/.salt-lint
* https://github.com/warpnet/salt-lint/pull/71
* https://pypi.org/project/salt-lint/0.0.10/
> feat(salt-lint): update `.salt-lint` configs for `v0.0.10`

- ssf/defaults.yaml
- ssf/files/default/kitchen.yml
- ssf/formulas.yaml
* Expedite this because `debian-10-develop-py3` is no longer working
after the new upstream release (`2019.2.2`)
* https://travis-ci.org/myii/template-formula/jobs/602164511#L447-L451
```salt
E: Repository 'https://repo.saltstack.com/py3/debian/9/amd64/latest stretch InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
STDERR: The command '/bin/sh -c apt-get update' returned a non-zero code: 100
---- End output of docker -H unix:///var/run/docker.sock build -f Dockerfile-kitchen20191024-6404-1oweo2f . ----
Ran docker -H unix:///var/run/docker.sock build -f Dockerfile-kitchen20191024-6404-1oweo2f . returned 100] on default-debian-10-develop-py3
```
> feat(kitchen): use `debian-10-master-py3` instead of `develop`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
> feat(formula): add `ntp-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/rabbitmq-formula/pull/52
---
To be merged _after_ #86.
> feat(formula): add `rabbitmq-formula`

- ssf/defaults.yaml
- ssf/files/default/.travis.yml
- ssf/files/tofs_ssf-formula/.travis.yml
* https://github.com/warpnet/salt-lint/issues/72#issuecomment-548738115
> feat(salt-lint): improve `salt-lint` invocation (better performance)

- ssf/defaults.yaml
- ssf/files/default/kitchen.yml
* Use temporary workaround for the current situation:
```bash
Step 1/19 : FROM netmanagers/salt-master-py2:amazonlinux-2
manifest for netmanagers/salt-master-py2:amazonlinux-2 not found
```
> feat(amazonlinux): use `develop` image until `master` is ready

- ssf/defaults.yaml
- ssf/files/default/inspec/inspec.yml
- ssf/files/tofs_openvpn-formula/Gemfile
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/openvpn-formula/pull/112
> feat(openvpn): implement Windows testing using `kitchen-vagrant`

- ssf/config/formulas.sls
- ssf/defaults.yaml
- ssf/files/default/kitchen.yml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/users-formula/issues/213
* https://github.com/saltstack-formulas/users-formula/pull/214
---
This also includes adapting the formula to deal with multiple suites under `verifier`, to reuse existing test suites where appropriate (in this case, running both the `default` and the `vimrc` tests).
> feat(users): add `vimrc` suite (inc. allow multiple suites under `verifier`)

- ssf/defaults.yaml
- ssf/files/default/.travis.yml
* https://docs.travis-ci.com/user/build-config-validation
> feat(travis): use build config validation (beta)

- ssf/defaults.yaml
- ssf/files/default/.travis.yml
* https://github.com/travis-ci/dpl/issues/1138#issuecomment-554988130
* https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release
* https://docs.travis-ci.com/user/build-config-validation
> feat(travis): opt-in to `dpl v2` to complete build config validation

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/netmanagers/salt-image-builder/issues/18
* https://github.com/netmanagers/salt-image-builder/commit/0b05d8f9cf718f1f68bba5196a81ee13e2f2789f
> feat(django): use default matrix after `centos-6` image fix

- .travis.yml
- pre-commit_semantic-release.sh
- ssf/defaults.yaml
- ssf/files/default/.travis.yml
- ssf/files/default/git/git_10_prepare.sh
- ssf/files/default/git/git_20_commit_push.sh
- ssf/files/default/git/git_30_create_PR.sh
- ssf/files/default/pre-commit_semantic-release.sh
* https://github.com/saltstack-formulas/template-formula/pull/180#issuecomment-558612422
> feat(travis): run `shellcheck` during lint job

- .travis.yml
- ssf/defaults.yaml
- ssf/files/default/.travis.yml
* https://github.com/saltstack-formulas/template-formula/pull/181#discussion_r351491871
> fix(travis): quote pathspecs used with `git ls-files`

- Gemfile
- ssf/defaults.yaml
- ssf/files/default/Gemfile
- ssf/files/tofs_openvpn-formula/Gemfile
- ssf/files/tofs_vault-formula/Gemfile
* Latest versions of `train` cause failure when running `kitchen verify`
* Downgrading to `3.2.0` until this is fixed upstream
* https://github.com/inspec/train/pull/544#issuecomment-566055052
> feat(gemfile): restrict `train` gem version until upstream fix

- .travis.yml
- ssf/defaults.yaml
- ssf/files/default/.travis.yml
* https://github.com/saltstack-formulas/bind-formula/issues/143#issuecomment-568197176
* https://travis-ci.com/saltstack-formulas/bind-formula/jobs/269513751#L266-L267
- `15.4.0` being used instead of newly released `15.14.0`
> feat(travis): use `major.minor` for `semantic-release` version

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/fail2ban-formula/issues/35#issuecomment-573162677
> feat(fail2ban): use `fail2ban.ng` in Kitchen

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/kjkeane/mattermost-formula/pull/25
> feat(mattermost): adjust Travis matrix to use `systemd` platforms only

- ssf/defaults.yaml
- ssf/formulas.yaml
* `amazonlinux-1-py2`: not a straight drop-in for `amazonlinux-2-py2`
* `amazonlinux-2-py3`: switch to this where possible instead
> feat: workaround issues with newly introduced `amazonlinux-1`

- .rubocop.yml
- ssf/defaults.yaml
- ssf/files/default/.rubocop.yml
* https://github.com/saltstack-formulas/template-formula/pull/188
> feat(rubocop): move `LineLength` cop from `Metrics` to `Layout`

- ssf/defaults.yaml
- ssf/files/tofs_salt-formula/.gitignore
- ssf/files/tofs_template-formula/.gitignore
* https://github.com/saltstack-formulas/salt-formula/pull/444
* https://github.com/saltstack-formulas/template-formula/pull/189
> feat(gitignore): track TOFS override files (`salt` & `template`)

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/firewalld-formula/pull/40
> feat(firewalld): relax rubocop `Metrics/BlockLength` for new tests

- ssf/defaults.yaml
- ssf/files/default/.travis.yml
- ssf/files/default/formula/libsaltcli.jinja
* Explained by @max-arnold:
- https://github.com/saltstack-formulas/template-formula/commit/69b632fbe613d4f99a48f59f64ec93c3897431c8#r38597329
---
Also a second commit to catch up with changes from:
* https://github.com/saltstack-formulas/template-formula/pull/194
> feat(libsaltcli): update `salt-ssh` detection for `enable_ssh_minions`

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://tree.taiga.io/project/myii-saltstack-formulas/task/187
* https://travis-ci.org/github/myii/telegraf-formula/builds/681360474 (before)
* https://travis-ci.org/github/myii/telegraf-formula/builds/682200993 (after)
Quoting from Slack #testing channel:
> Final issue with this test run: the `telegraf-formula` is failing
> completely, due to `toml` issues:
> https://travis-ci.org/github/myii/telegraf-formula/builds/681360474.
> I'm vaguely aware that something has changed in this regard for Sodium,
> so probably the formula needs to change?
> 
> ```
> ID: telegraf/config/install
> Function: file.managed
>     Name: /etc/telegraf/telegraf.conf
>   Result: False
>  Comment: Unable to manage file: Jinja error: module 'toml' has no attribute 'dumps'
>    Traceback (most recent call last): …
```
> feat(telegraf): avoid `master` instances due to `toml` issues [skip ci]

- ssf/formulas.yaml
This reverts commit 5f75ebda95a2cf79e4daef800eee0765056de38b.
* https://github.com/saltstack-formulas/telegraf-formula/pull/7
---
This is not a true reversion, in the sense that there was a mistake made.  Once the fix became clear and was applied, it made sense to link this back to the previous commit.
> revert(telegraf): avoid `master` instances due to `toml` issues

- pillar.example
- ssf/.github/workflows/commitlint.yml
- ssf/defaults.yaml
- ssf/files/default/.github/workflows/commitlint.yml
- ssf/formulas.yaml
* https://github.com/marketplace/actions/commit-linter
---
Note: `apt-formula` already done since testing here:
* https://github.com/saltstack-formulas/apt-formula/pull/62
> feat(workflows/commitlint): manage across formulas

- CODEOWNERS
- pillar.example
- ssf/config/formulas.sls
- ssf/defaults.yaml
- ssf/files/default/CODEOWNERS
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
A couple of formulas have already been managed while developing this:
* [`libvirt-formula`](https://github.com/saltstack-formulas/libvirt-formula/blob/e8760b7f47c507182f7235b2d3d94e4f95f0ee1b/CODEOWNERS)
* [`salt-formula`](https://github.com/saltstack-formulas/salt-formula/blob/3a46ca426b15c64c507b78d37782c45ff02c75a8/CODEOWNERS)
When no global owner is defined (which will be most of the formulas for now), the file will have a comment header at the top, which looks like this:
* [`libvirt-formula` without global owner](https://github.com/saltstack-formulas/libvirt-formula/commit/614f2e27f7de7e9f74dcbc958bb317682293b4fd)
Obviously, when this PR is merged, the file will be managed here as well.
> feat(codeowners): manage across formulas

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/jetbrains-rider-formula/pull/5
> feat(formula): add `jetbrains-rider-formula`

- .travis.yml
- .yamllint
- ssf/config/formulas.sls
- ssf/defaults.yaml
- ssf/files/default/.travis.yml
- ssf/files/tofs_arvados-formula/.travis.yml
- ssf/formulas.yaml
* Use `%2F` for the forward slash in the topic name:
- https://docs.travis-ci.com/user/triggering-builds/
- https://www.degraeve.com/reference/urlencoding.php
* Use Travis `if` conditional rather than `secret` encrypted enviroment
variable workaround suggested:
- Not a secret, just the bot's API key
- Need to be able to modify parts of the URL in certain situations,
such as the weekly `master` branch tests
- References:
+ https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables
+ https://github.com/travis-ci/travis-ci/issues/329
+ https://github.com/travis-ci/travis-ci/issues/1094
+ https://github.com/travis-ci/travis-ci/issues/5063
+ https://github.com/travis-ci/travis-ci/issues/6100
+ https://github.com/mozilla/build-tools/commit/c13a297
> feat(travis): push notifications to `saltstack-formulas.zulipchat.com`

- ssf/defaults.yaml
- ssf/files/default/kitchen.yml
- ssf/formulas.yaml
Includes:
* fix(kitchen): apply `SCP` workaround for `opensuse-leap-15.2` as well
> feat(salt): adjust matrix to add `opensuse-leap-15.2`

- ssf/defaults.yaml
- ssf/formulas.yaml
* Fix https://travis-ci.org/github/myii/logrotate-formula/builds/691020719
> feat(logrotate): use latest pre-salted images (`platforms_new`)

- ssf/defaults.yaml
- ssf/formulas.yaml
* Would only make a difference if Zulip had been configured for the
previous formula location
* Update `docs/README.rst` in the actual formula to finalise the badges
* Use this PR as a general clean-up of the formula structure here in the
`ssf-formula`
> feat(suricata): finalise structure after transfer to main org

- ssf/defaults.yaml
- ssf/files/default/formula/libtofs.jinja
- ssf/libtofs.jinja
* https://github.com/saltstack-formulas/libvirt-formula/pull/77
> feat(libtofs.jinja): use Black-inspired Jinja formatting

- ssf/defaults.yaml
- ssf/files/tofs_sudoers-formula/inspec/README.md
- ssf/formulas.yaml
* Prompted by https://github.com/saltstack-formulas/sudoers-formula/pull/65
> feat(sudoers): verify `map.jinja` using InSpec

- .yamllint
- pillar.example
- ssf/config/formulas.sls
- ssf/defaults.yaml
- ssf/files/default/.pre-commit-config.yaml
- ssf/files/default/.rstcheck.cfg
- ssf/files/default/.travis.yml
- ssf/files/default/bin/install-hooks
- ssf/files/tofs_.github/docs/CONTRIBUTING.rst
- ssf/files/tofs_arvados-formula/.travis.yml
- ssf/formulas.yaml
Making a start on this.
Think rolling this out is best done in stages:
- keep `yamllint` files and ignores in `.yamllint`
- roll out to all formulas
- remove standalone lint jobs
- move `yamllint` files and ignores from `.yamllint` to `.pre-commit-config.yaml`; and
- implement `shellcheck.exclude_paths` in `.pre-commit-config.yaml`
Things to resolve in this PR:
> feat(pre-commit): add `pre-commit`

- .pre-commit-config.yaml
- ssf/config/formulas.sls
- ssf/defaults.yaml
- ssf/files/default/.pre-commit-config.yaml
- ssf/formulas.yaml
Completes #259 except for 5 remaining formulas.
---
Couple of formulas already pushed:
* https://github.com/saltstack-formulas/apache-formula/commit/233111af11dd25b573928e746f19b06bcdbf19b9
* https://github.com/saltstack-formulas/apt-formula/commit/4cf4741228a1210c52f994bec071bfaf6e45609d
> feat(pre-commit): enable/disable `rstcheck` as relevant

- ssf/defaults.yaml
- ssf/files/tofs_.github/docs/CONTRIBUTING.rst
- ssf/files/tofs_apache-formula/.salt-lint
- ssf/formulas.yaml
- ssf/libcimatrix.jinja
* https://github.com/saltstack-formulas/apache-formula/pull/283
> feat(apache): review PR 283

- .gitlab-ci.yml
- ssf/defaults.yaml
- ssf/files/default/.gitlab-ci.yml
Use a separate job for `rubocop` other than the one potentially run by `pre-commit`
- The `pre-commit` check will only be available for formulas that pass the default
`rubocop` check -- and must continue to do so
- This job is allowed to fail, so can be used for all formulas
- Furthermore, this job uses all of the latest `rubocop` features & cops,
which will help when upgrading the `rubocop` linter used in `pre-commit`
> feat(gitlab-ci): add `rubocop` linter (with `allow_failure`)

- .gitlab-ci.yml
- ssf/defaults.yaml
- ssf/files/default/.gitlab-ci.yml
Avoid using `${CI_PROJECT_URL}` (the local repo's URL) since that leads
to `upstream/master` only pointing to the local repo's `master` branch,
which could be many commits behind, resulting in spurious `commitlint`
failures.
> feat(commitlint): ensure `upstream/master` uses main repo URL

- ssf/defaults.yaml
- ssf/files/default/kitchen.yml
- ssf/formulas.yaml
Includes:
```
feat(saltimages): update with latest changes from `salt-image-builder`
Add all deprecated images in the sub-section at the bottom, so that the
Jinja section in the `kitchen.yml` template can be simplified as well.
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/68
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/69
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/71
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/72
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/74
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/75
* …
```
> feat(formulas): update `platforms_new_saltimages`

- ssf/defaults.yaml
- ssf/formulas.yaml
* Prompted by:
- https://github.com/saltstack-formulas/php-formula/pull/214
- https://github.com/saltstack-formulas/php-formula/pull/215
- https://github.com/saltstack-formulas/php-formula/issues/216
- https://github.com/saltstack-formulas/php-formula/issues/217
> feat(php): manage `map.jinja` verification

- ssf/defaults.yaml
- ssf/files/default/formula/_mapdata/_mapdata.jinja
- ssf/files/default/formula/_mapdata/init.sls
- ssf/files/default/inspec/controls/_mapdata_spec.rb
- ssf/formulas.yaml
Notes:
* Main commit:
- Realised that the last batch of PRs (#281, #282 & #283) were setting up verification files without a top-level key.
- Yet, the v5 `map.jinja` formula (`openssh`) did have multiple top-level keys.
- In conversations with @javierbertoli and @baby-gnu, worked out a plan to have a standard format across all verification files, with a `values` top-level key.
* feat(php): add `rubocop` linter to `pre-commit`
- `rubocop` already fixed during the previous PR (#283):
- https://github.com/saltstack-formulas/php-formula/pull/221
* feat(_mapdata_spec): dump YAML back to string for better diffs
- Provide a full breakdown of the method used to prepare the comparison between both files.
- Tested this with the newest `inspec` gem in the hope that the diff would work but still …
> feat(_mapdata): use top-level `values` for `map.jinja` dump files

- ssf/defaults.yaml
- ssf/formulas.yaml
Establish the standard method for formulas, replacing the initial version that was used (i.e. `yaml_dump`).
> feat(_mapdata): manage `map.jinja` verification (replace `yaml_dump`)

- ssf/defaults.yaml
- ssf/files/default/formula/_mapdata/init.sls
- ssf/formulas.yaml
There is no more need to check for the `map_jinja` version.
> fix(_mapdata): single variable should be at top level under `values`

- ssf/defaults.yaml
- ssf/files/default/inspec/README.md
- ssf/files/default/inspec/libraries/system.rb
- ssf/files/default/kitchen.yml
- ssf/formulas.yaml
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/78
Regarding changes to `kitchen.yml`, confirmed that the
`max_ssh_sessions` was also needed for `opensuse/tumbleweed`:
* https://gitlab.com/myii/openvpn-formula/-/jobs/983088326#L421
---
Only a couple of formulas are using `*platforms_new_saltimages` so have the actual platforms update.  The rest of the formulas are having the latest version of the `share` InSpec suite pushed to them.
> feat(saltimages): update with latest changes from `salt-image-builder`

- Gemfile
- Gemfile.lock
- ssf/defaults.yaml
- ssf/files/default/Gemfile
- ssf/files/default/Gemfile.lock
- ssf/files/tofs_openssh-formula/Gemfile
- ssf/files/tofs_openssh-formula/Gemfile.lock
- ssf/files/tofs_openvpn-formula/Gemfile
- ssf/files/tofs_openvpn-formula/Gemfile.lock
Idea was prompted by an unnecessary failure on Tumbleweed during the
`kitchen create` phase.
https://gitlab.com/myii/fail2ban-formula/-/jobs/1033337903
```console
( 8/10) Installing: openssh-server-8.4p1-4.1.x86_64 [...error]
Installation of openssh-server-8.4p1-4.1.x86_64 failed:
Error: Subprocess failed. Error: RPM failed: find: '/etc/init.d/rc[35].d': No such file or directory
ERROR: neither useradd nor busybox found!
error: %prein(openssh-server-8.4p1-4.1.x86_64) scriptlet failed, exit status 1
error: openssh-server-8.4p1-4.1.x86_64: install failed
error: openssh-server-8.4p1-3.1.x86_64: erase skipped
Abort, retry, ignore? [a/r/i] (a): a
Warning: %posttrans scripts skipped while aborting:
sudo-1.9.5p2-1.2.x86_64.rpm
openssh-server-8.4p1-4.1.x86_64.rpm
Problem occurred during or after …
```
> feat(gemfile+lock): use `ssf` customised `kitchen-docker` repo

- ssf/defaults.yaml
- ssf/files/default/.rubocop.yml
- ssf/files/default/inspec/controls/_mapdata.rb
* https://github.com/saltstack-formulas/java-formula/pull/15
> feat(rubocop): allow use of `YAML.load` for `_mapdata.rb`

- ssf/config/formulas.sls
- ssf/defaults.yaml
- ssf/files/default/.gitlab-ci.yml
- ssf/files/default/kitchen.yml
- ssf/formulas.yaml
- ssf/libcimatrix.jinja
Establish all of the following changes:
* Use wildcards for (but *maintain* current ordering of entries when rendered):
- NOTE: Use new values to ensure reverse compatibility,
where need to be able to use the original, non-wildcard method instead
- To filter out `platforms` that must not be included (and `platform_matrix`)
- `platform_suite` inclusions and exclusions
- `platforms_matrix` (after initial testing)
* Use latest pre-salted images
- Active unique combination of platforms for all formulas:
+ E.g. `apt-formula` must only have Debian-based platforms in the list
+ Based around idea of supplying these in the `FORMULA` file
+ Active became the wildcards that have been implemented
* Move `dependencies` to the top in each suite (where used)
* Use new solution to replace …
> feat: overhaul CI implementation and use latest pre-salted images

- ssf/defaults.yaml
- ssf/files/default/kitchen.yml
Pretty straightforward change, hopefully.
Comments?
Configuration of:
```
firefox:
inspec_suites_kitchen:
0:
inspec_yml:
summary: >-
Verify that the firefox formula is setup and configured correctly
supports:
- windows
provisioner:
state_top:
- '*':
- .
verifier:
controls:
- .package.install
- .gpo.install
- .gpo.config
```
would produce:
```
suites:
- name: default
provisioner:
state_top:
base:
'*':
- firefox
pillars:
top.sls:
base:
'*':
- firefox
pillars_from_files:
firefox.sls: pillar.example
verifier:
inspec_tests:
- path: test/integration/default
controls:
- firefox.package.install
- firefox.gpo.install
- firefox.gpo.config
```
> feat(kitchen): allow specifying InSpec `controls`

- ssf/defaults.yaml
- ssf/files/default/kitchen.vagrant.yml
Also includes:
* feat(salt): avoid FreeBSD `master` boxes (unused in the formula)
> feat(vagrant): add FreeBSD 13.0 testing across formulas

- ssf/defaults.yaml
- ssf/files/default/kitchen.vagrant.yml
- ssf/files/default/kitchen.yml
- ssf/formulas.yaml
- ssf/libcimatrix.jinja
feat(saltimages): update with latest changes from `salt-image-builder`
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/89
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/90
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/91
> feat: use latest pre-salted images for all formulas (inc. `3003`)

- ssf/defaults.yaml
- ssf/files/default/kitchen.yml
The workaround has been added to the pre-salted images now:
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/93
> feat(kitchen): remove Fedora legacy `crypto-policies` workaround

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/docker-formula/pull/285
> feat(docker): review PR 285

- Gemfile.lock
- ssf/defaults.yaml
- ssf/files/default/Gemfile.lock
- ssf/files/tofs_openssh-formula/Gemfile.lock
- ssf/files/tofs_openvpn-formula/Gemfile.lock
* https://github.com/advisories/GHSA-jxhc-q857-3j6g/dependabot?query=user%3Asaltstack-formulas
- Regular Expression Denial of Service in Addressable templates
> feat(gemfile.lock): bump `addressable` from `2.7.0` to `2.8.0`

- ssf/defaults.yaml
- ssf/formulas.yaml
Re-enable once the pre-salted Vagrant boxes have been updated with the
`py38-*`-based Salt packages.
See:
* https://github.com/saltstack/salt-bootstrap/pull/1574
> feat(salt): disable FreeBSD until pre-salted boxes updated

- ssf/defaults.yaml
- ssf/formulas.yaml
This reverts commit f638761348eec9debef00d6e83bc315886222c97.
Issue now resolved and confirmed by testing with Kitchen locally:
* https://github.com/phusion/passenger/issues/2364
> revert(nginx): disable failing instance until upstream issue resolved

- ssf/defaults.yaml
- ssf/files/default/kitchen.windows.yml
- ssf/files/default/kitchen.yml
- ssf/formulas.yaml
* Move the `provisioner` block above `platforms`.
- Ordering becomes `driver`, `provisioner`, `platforms`, `verifier` and finally `suites`.
- The main reason is because `platforms` can override the general values provided under `provisioner`, similar to the `driver` overrides.
- An example of this can be seen here:
+ https://github.com/saltstack/salt-bootstrap/blob/3690eeec50199954522e76c33fc7d49fc620fabf/kitchen.vagrant.yml#L14-L41
* Switch to a general `run_command` of `/usr/lib/systemd/systemd` instead of `/lib/systemd/systemd`.
- There are actually more platforms that are based on that in reality.
- Noticed the discrepancy between our `kitchen.yml` and the one in the `salt-bootstrap` repo and when investigating, found that ours wasn't accurate.
- Relates to this merged PR: …
> feat(kitchen): move `provisioner` block & update `run_command`

- .yamllint
- ssf/config/formulas.sls
- ssf/defaults.yaml
- ssf/files/default/.cirrus.yml
- ssf/files/default/.github/workflows/kitchen.vagrant.yml
- ssf/files/default/.github/workflows/kitchen.windows.yml
- ssf/files/default/.github/workflows/kitchen.yml
- ssf/files/default/.gitlab-ci.yml
- ssf/files/default/.travis.yml
- ssf/files/default/.yamllint
- ssf/files/default/kitchen.yml
- ssf/formulas.yaml
- ssf/libcimatrix.jinja
```console
feat(saltimages): update with latest changes from `salt-image-builder`
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/114
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/115
```
* Main change here is introducing Debian 11 Bullseye pre-salted images.
* In order to use these Debian 11 images across all formulas, also had to implement the ability to use `allow_failures` for instances, since a number of formulas don't have upstream repos available for Bullseye yet.
Breakdown of where `allow_failures` has been used:
* Debian 11, awaiting upstream repo:
- `nginx-formula` (`passenger` suite)
- `node-formula`
- `packages-formula` (which fails due to the dependency on the `node-formula`)
- …
> feat: add Debian 11 Bullseye & update `yamllint` configuration

- pillar.example
- ssf/defaults.yaml
- ssf/formulas.yaml
These formulas also show up on the security warnings for the
organisation; ideally, they should be managed like the rest of the
formulas but implementing a basic solution for the `Gemfile` and
`Gemfile.lock` files right now.  Also includes management of the
`commitlint` GitHub Action as well as the `CODEOWNERS` file.
* backupninja-formula
* charles-formula
* dbeaver-formula
* diaspora-formula
* kubernetes-formula
* nextcloud-formula
* rlang-formula
* rstudio-formula
* wireguard-formula
* zookeeper-formula
> feat(formulas): add basic management for `Gemfile+lock` formulas

- pillar.example
- ssf/defaults.yaml
- ssf/formulas.yaml
These formulas were already "available" here, commented out, for future
`CODEOWNERS` inclusion.  This commit finally makes use of those, as well
as managing the gems there.
* aegir-formula
* bareos-formula
* rundeck-formula
> feat(formulas): add basic management for `Gemfile+lock` formulas (previously commented out)

- ssf/defaults.yaml
- ssf/formulas.yaml
```console
refactor(formulas): use wildcards again where possible after `16.04` EOL
```
Additional commit finalises 9750033f9975dbe74d52090c01a9cc7c9a6c6e8c.
> feat(postgres): add `repo` suite

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/118
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/120
- Removed AlmaLinux `3003.1` & `3003.0` without an MR (i.e. in a separate commit)
- https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/commit/dda500ba9da7
> feat(saltimages): update with latest changes from `salt-image-builder` (`3003.2`)

- ssf/defaults.yaml
- ssf/formulas.yaml
Also contains temporary fix for the `node-formula` CI dependency until the following PR is finalised and merged:
* https://github.com/saltstack-formulas/node-formula/pull/59
> feat(packages): manage `map.jinja` verification

- .pre-commit-config.yaml
- ssf/files/default/.gitlab-ci.yml
- ssf/files/default/.pre-commit-config.yaml
- ssf/files/default/pre-commit_semantic-release.sh
- ssf/files/default/release.config.js
- ssf/formulas.yaml
Includes a temporary exclusion for the `.pre-commit-config.yaml` template (in the file itself as well), which should be removed when no longer needing to use it as a Jinja template (i.e. when all formulas are configured for Antora).
> feat(antora): add initial support (only for `apache-formula` currently)

- .gitignore
- ssf/defaults.yaml
- ssf/files/default/.gitignore
- ssf/formulas.yaml
Also includes:
* feat(freebsd): deprecate `11.4` (EOL: 2021-09-30)
* feat(gitignore): allow test pillar `top.sls` (`template-formula` PR)
- https://github.com/saltstack-formulas/template-formula/pull/238
> feat(saltimages): update with latest changes from salt-image-builder (3003.3, 3002.7 & 3001.8)

- ssf/defaults.yaml
- ssf/files/default/kitchen.vagrant.yml
- ssf/files/default/kitchen.windows.yml
- ssf/files/default/kitchen.yml
- ssf/formulas.yaml
References:
* https://github.com/inspec/kitchen-inspec#use-inputs-with-your-inspec-profiles
* https://joachim8675309.medium.com/testing-chef-cookbooks-with-inspec-c18ec1119c94
- Note, that this refers to `attributes`, which have since been renamed to `inputs`.
* https://www.reddit.com/r/chef_opscode/comments/8jfars/how_do_you_access_kitchenyml_attributes_in_inspec/
> feat(salt): merge all test suites into single suite (using `pillars_from_directories`, `test/salt/pillar/top.sls` and `platforms.verifier.inputs`)

- ssf/defaults.yaml
- ssf/files/default/.gitlab-ci.yml
- ssf/formulas.yaml
- ssf/libcimatrix.jinja
feat(saltimages): update with latest changes from `salt-image-builder`
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/128
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/129
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/130
---
Also includes:
* feat(gitlab-ci): allow failure for new/unstable platforms in general
- Whereas the Debian 11 (and other) instances are being allowed to fail selectively where needed in specific formulas, this is too much to do for the new (CentOS Stream 8) or unstable (Fedora 35 & OpenSUSE Tumbleweed) platforms.  Allow failure for these across all instances until the situation stabilises.
* feat(openbsd): deprecate `6.8` (EOL: …
> feat: use latest pre-salted images for all formulas (inc. `3004`)

- ssf/defaults.yaml
- ssf/files/default/kitchen.windows.yml
- ssf/files/default/test/integration/share/libraries/system.rb
* https://github.com/actions/virtual-environments/issues/4312
---
Also includes:
* feat(proxy): remove literal `C:\salt\` from `salt-call` command
- Prepare for `3004`, which no longer uses this non-standard path.
> feat(proxy): replace deprecated Windows `2016` with `2022`

- ssf/defaults.yaml
- ssf/files/default/kitchen.vagrant.yml
Includes:
* feat(vagrant): allow `synced_folders` on FreeBSD 13.0 (bug fixed)
- https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=255208
> feat(vagrant): replace FreeBSD 12.2 with 12.3

- ssf/defaults.yaml
- ssf/formulas.yaml
Use to fix Arch Linux `cron` installation and testing in the formula:
* https://github.com/saltstack-formulas/logrotate-formula/pull/60#issuecomment-1013031092
> feat(logrotate): use `cron-formula` dep instead of single `cron` state

- ssf/defaults.yaml
- ssf/formulas.yaml
- ssf/map.jinja
Also includes:
* revert(packages): use `test-kitchen` branch for `node-formula` dependency
* feat(node): remove `test/salt/pillar/repo.sls` from `yamllint` ignores
> feat(map.jinja): remove formulas with no active `semrel_files`

- ssf/defaults.yaml
- ssf/files/default/formula/libmatchers.jinja
- ssf/files/default/formula/libsaltcli.jinja
* https://github.com/saltstack-formulas/openssh-formula/issues/203
* https://github.com/saltstack-formulas/openssh-formula/pull/204
> feat(libsaltcli+libmatchers): update to ensure Salt client API detection

- ssf/defaults.yaml
- ssf/files/default/test/integration/share/libraries/system.rb
Use to remove duplicate code introduced in:
* https://github.com/saltstack-formulas/nginx-formula/pull/289
* https://github.com/saltstack-formulas/postgres-formula/pull/322
* https://github.com/saltstack-formulas/docker-formula/pull/312
---
Tested out in the `cert-formula` to confirm all working as expected:
* https://gitlab.com/myii/cert-formula/-/pipelines/470201444
> feat(system.rb): add `build_platform_codename`

- ssf/files/default/formula/libmapstack.jinja
- ssf/files/default/formula/libmatchers.jinja
- ssf/files/default/formula/libsaltcli.jinja
* https://github.com/saltstack-formulas/template-formula/pull/243
* https://github.com/saltstack-formulas/template-formula/pull/244
* https://github.com/saltstack-formulas/template-formula/pull/245
* https://github.com/saltstack-formulas/template-formula/pull/246
Closes #417.
> feat(template): review PRs 243, 244, 245 & 246

- Gemfile.lock
- ssf/defaults.yaml
- ssf/files/default/Gemfile.lock
- ssf/files/tofs_openssh-formula/Gemfile.lock
- ssf/files/tofs_openvpn-formula/Gemfile.lock
* https://github.com/myii/salt/commit/8bef3a81ec695e76ac8c5048074ec933ec2e83ca
- Includes another extra commit to avoid recent `include` regression in `master` branch.
Test results:
* https://saltstack-formulas.zulipchat.com/#narrow/stream/239693-CI/topic/myii-ci.2F2022-W12a
> feat(gemfile.lock): use `bundle update` to get latest gems [2022-W12]

- Gemfile.lock
- ssf/defaults.yaml
- ssf/files/default/Gemfile.lock
- ssf/files/tofs_openssh-formula/Gemfile.lock
- ssf/files/tofs_openvpn-formula/Gemfile.lock
* https://github.com/myii/salt/commit/613f4f5767465fbb0818f6d1e18e68e64463713c
Test results:
* https://saltstack-formulas.zulipchat.com/#narrow/stream/239693-CI/topic/myii-ci.2F2022-W14a
> feat(gemfile.lock): use `bundle update` to get latest gems [2022-W14]

- Gemfile.lock
- ssf/defaults.yaml
- ssf/files/default/Gemfile.lock
- ssf/files/tofs_openssh-formula/Gemfile.lock
- ssf/files/tofs_openvpn-formula/Gemfile.lock
* https://github.com/myii/salt/commit/18c9b7e3e5f442df64eed83dcc69bad6dc602bf1
Test results:
* https://saltstack-formulas.zulipchat.com/#narrow/stream/239693-CI/topic/myii-ci.2F2022-W15a
> feat(gemfile.lock): use `bundle update` to get latest gems [2022-W15]

- ssf/defaults.yaml
- ssf/formulas.yaml
Use this to fix the formula for Amazon Linux 2 & Fedora 36.
> feat(tomcat): use `pillars_from_directories` & test `pillar/top.sls`

- Gemfile.lock
- ssf/defaults.yaml
- ssf/files/default/Gemfile.lock
- ssf/files/tofs_openssh-formula/Gemfile.lock
- ssf/files/tofs_openvpn-formula/Gemfile.lock
* https://github.com/myii/salt/commit/a16af0644a2ca4181ba4ec42c9b679bf901a145f
Test results:
* https://saltstack-formulas.zulipchat.com/#narrow/stream/239693-CI/topic/myii-ci.2F2022-W19a
> feat(gemfile.lock): use `bundle update` to get latest gems [2022-W19]

- Gemfile.lock
- ssf/defaults.yaml
- ssf/files/default/Gemfile.lock
- ssf/files/tofs_openssh-formula/Gemfile.lock
- ssf/files/tofs_openvpn-formula/Gemfile.lock
* https://github.com/myii/salt/commit/6a9da114ec9260ffad66065919b7f76b421cf176
Test results:
* https://saltstack-formulas.zulipchat.com/#narrow/stream/239693-CI/topic/myii-ci.2F2022-W23a
> feat(gemfile.lock): use `bundle update` to get latest gems [2022-W23]

- .pre-commit-config.yaml
- ssf/defaults.yaml
- ssf/files/default/.pre-commit-config.yaml
- ssf/formulas.yaml
Also includes:
Now required after enabling pre-commit.ci across the org.
* github.com/rubocop-hq/rubocop: v1.25.1 → v1.30.1
- https://github.com/rubocop-hq/rubocop/compare/v1.25.1...v1.30.1
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/145
> feat(pre-commit): update configuration inc. for pre-commit.ci
