- pillar.example
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* Usually would have to add to `defaults.yaml` as well but already done
from earlier testing
> feat(formula): add `users-formula`

- .travis.yml
- .yamllint
- pillar.example
- ssf/defaults.yaml
- ssf/files/default/inspec/inspec.yml
- ssf/formulas.yaml
* feat(travis): add `yamllint` check to `commitlint` stage
> feat(yamllint): include for this repo and apply rules throughout

- .travis.yml
- .yamllint
- pillar.example
- ssf/config/formulas.sls
- ssf/defaults.yaml
- ssf/files/default/.travis.yml
- ssf/files/default/.yamllint
- ssf/files/default/inspec/inspec.yml
- ssf/files/default/kitchen.yml
- ssf/formulas.yaml
* Prepare this alongside submitting all of the PRs
* Main `template-formula` PR with links to all of the other PRs:
- https://github.com/saltstack-formulas/template-formula/pull/159
> feat(yamllint): configure for all `semrel_formulas`

- ssf/defaults.yaml
- ssf/formulas.yaml
* Done alongside fixing InSpec tests not running
---
* https://github.com/saltstack-formulas/bind-formula/pull/136
> feat(bind): re-enable `fedora`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/timezone-formula/pull/14
> feat(formula): add `timezone-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/sysctl-formula/pull/23
> feat(formula): add `sysctl-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/cron-formula/pull/5
> feat(formula): add `cron-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/vsftpd-formula/pull/7
> feat(formula): add `vsftpd-formula`

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/libvirt-formula/pull/51
* https://github.com/saltstack-formulas/libvirt-formula/pull/53#discussion_r318455954
> feat(libvirt): add openSUSE to supported platform

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/php-formula/pull/197
> feat(php): use separate suite for `ubuntu` (yamllint)

- ssf/defaults.yaml
- ssf/formulas.yaml
* Based on the discussions in the following merged PR:
- https://github.com/saltstack-formulas/template-formula/pull/148
> feat(formulas): replace EOL pre-salted images

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/vim-formula/pull/42
> feat(formula): add `vim-formula`

- ssf/defaults.yaml
- ssf/formulas.yaml
* Custom version of #16 (23f3b80) for `ufw-formula`
> feat(ufw): replace EOL pre-salted images

- ssf/defaults.yaml
- ssf/files/default/inspec/inspec.yml
- ssf/files/default/kitchen.yml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/libvirt-formula/pull/56
Process included these improvements:
* feat(inspec.yml): add `depends` handling
* feat(kitchen.yml): prevent suite inclusion if `includes: *includes_NONE`
> feat(libvirt): incorporate upstream changes

- .travis.yml
* Automated using https://github.com/myii/ssf-formula/pull/22
> ci(travis): use `dist: bionic`

- ssf/defaults.yaml
- ssf/formulas.yaml
* Found while working on #27, i.e.:
- https://github.com/saltstack-formulas/template-formula/issues/164
> feat(openvpn): use standard test pillar path

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/php-formula/pull/178
> feat(php): implement TOFS

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* Use directly on formula to produce a `semantic-release` PR
> feat(formula): add `redis-formula`

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/openssh-formula/pull/168
> feat(openssh): use `openssh.config` as `state_top`

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/vault-formula/pull/35#issuecomment-510046931
* https://freenode.logbot.info/saltstack-formulas/20190711#c2390145
> feat(vault): use `kitchen verify` instead of `kitchen test`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/exim-formula/pull/9
> feat(formula): add `exim-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/apt-cacher-formula/pull/18
> feat(formula): add `apt-cacher-formula`

- pillar.example
- ssf/config/formulas.sls
- ssf/defaults.yaml
- ssf/files/default/git/git_20_commit_push.sh
- ssf/files/default/kitchen.yml
- ssf/formulas.yaml
BREAKING CHANGE: Multiple arguments have been added to the `commit_push`
shell script.  This includes logically reordering the arguments.
BREAKING CHANGE: The pillar structure has been modified according to the
changes made.
> feat: allow pushing directly to upstream remote

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/stunnel-formula/pull/7
> feat(formula): add `stunnel-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/default/.github/ISSUE_TEMPLATE/bug_report.md
- ssf/files/default/.github/ISSUE_TEMPLATE/feature_request.md
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/template-formula/pull/171
> feat(issues): manage templates for all `semrel_formulas`

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/syslog-ng-formula/pull/23
> feat(syslog-ng): update formula to latest standards

- ssf/config/formulas.sls
- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/syslog-ng-formula/pull/24
---
Note, original PR was here:
* https://github.com/saltstack-formulas/syslog-ng-formula/pull/14
> feat(syslog-ng): implement TOFS

- ssf/defaults.yaml
- ssf/files/tofs_vault-formula/Gemfile
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/vault-formula/pull/43#issuecomment-533936364
---
Had a number of steps to be done before this could be realised.  These were originally included in this PR but have been split into #46, to allow that to be merged.
> feat(vault): split suites across instances leaving one running all

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/libvirt-formula/pull/60
> feat(libvirt): implement TOFS

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/n-rodriguez/telegraf-formula/issues/1
---
Updated:
* https://github.com/saltstack-formulas/telegraf-formula/issues/1
> feat(formula): add `telegraf-formula`

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/exim-formula/pull/13
> feat(exim): implement TOFS

- ssf/config/formulas.sls
- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/apt-cacher-formula/pull/19
> feat(apt-cacher): implement TOFS

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/zabbix-formula/pull/130#issuecomment-541303953
> feat(zabbix): use `fedora-29` instead of `fedora-30` (for reliability)

- ssf/config/formulas.sls
- ssf/defaults.yaml
* https://github.com/saltstack-formulas/.github/pull/1
---
Before running this, made sure that all of the `README` files had their `CONTRIBUTING` link updated to the file in this repo.
The `apt-formula` commit won't show below because it was already pushed during testing.
> feat(contributing): remove from all `semrel_formulas`

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/libvirt-formula/pull/62
> feat(libvirt): merge `rubocop` linter into main `lint` job

- .travis.yml
- .yamllint
- pillar.example
- ssf/defaults.yaml
- ssf/formulas.yaml
* Specifically: `quote-type: 'single'`
> style(yamllint): apply rule `quoted-strings` throughout the formula

- .yamllint
- ssf/files/tofs_ssf-formula/.travis.yml
- ssf/files/tofs_ssf-formula/.yamllint
- ssf/formulas.yaml
> feat(ssf): add TOFS overrides to ensure `quoted-strings` rule fulfilled

- ssf/defaults.yaml
- ssf/files/default/.travis.yml
- ssf/files/tofs_ssf-formula/.travis.yml
* https://github.com/saltstack-formulas/cron-formula/pull/4
> feat(saltcheck): add support in `.travis.yml` templates

- ssf/defaults.yaml
- ssf/files/default/kitchen.yml
* https://github.com/saltstack-formulas/vault-formula/pull/50#discussion_r344262345
* https://github.com/saltstack-formulas/vault-formula/pull/50#discussion_r344290629
* https://github.com/orgs/saltstack-formulas/teams/wg/discussions/13
> feat(kitchen): use `stable` for `amazonlinux-1` bootstrap

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/rabbitmq-formula/pull/53#issuecomment-553480289
> feat(rabbitmq): add `latest` suite

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/nfs-formula/pull/33
> feat(formula): add `nfs-formula`

- ssf/defaults.yaml
- ssf/files/tofs_fail2ban-formula/pre-commit_semantic-release.sh
- ssf/files/tofs_fail2ban-formula/release.config.js
* https://github.com/saltstack-formulas/fail2ban-formula/issues/34#issuecomment-539986988
* https://github.com/saltstack-formulas/fail2ban-formula/issues/35
> feat(fail2ban): add notification about upcoming `ng` promotion

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
Prepared this when evaluating:
* https://github.com/saltstack-formulas/mongodb-formula/pull/72
> feat(formula): add `mongodb-formula`

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/apt-formula/pull/60
> feat(apt): add `unattended` suite

- ssf/defaults.yaml
- ssf/files/default/.rubocop.yml
- ssf/files/default/.travis.yml
* https://github.com/saltstack-formulas/template-formula/pull/180
* https://github.com/saltstack-formulas/template-formula/pull/183
> feat(template): improve reusability

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/rabbitmq-formula/pull/57
> feat(rabbitmq): add new `config_files` state to suites

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/rabbitmq-formula/pull/58
> feat(rabbitmq): manage env file

- ssf/defaults.yaml
- ssf/formulas.yaml
* Close https://github.com/saltstack-formulas/libvirt-formula/issues/64
* Based on:
- https://github.com/saltstack-formulas/libvirt-formula/pull/66
- https://github.com/saltstack-formulas/libvirt-formula/pull/67
- https://github.com/saltstack-formulas/libvirt-formula/pull/68
> feat(libvirt): update Travis matrix after recent platform fixes

- pillar.example
- ssf/defaults.yaml
- ssf/formulas.yaml
* https://freenode.logbot.info/saltstack-formulas/20200108#c3052081-c3052088
> feat(formula): add `mattermost-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/default/kitchen.yml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/packages-formula/pull/61
* Previous PR:
- https://github.com/saltstack-formulas/packages-formula/pull/54
> feat(formula): add `packages-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/hostsfile-formula/pull/28
> feat(formula): add `hostsfile-formula`

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/template-formula/pull/180
> feat(template): update to use `TEMPLATE` for reusability

- ssf/defaults.yaml
- ssf/formulas.yaml
* Broken: https://travis-ci.com/saltstack-formulas/salt-formula/jobs/286756542
* Tested: https://travis-ci.org/myii/salt-formula/jobs/649882733
> feat(salt): fix `amazonlinux-2-py3` (kitchen+travis+inspec)

- ssf/defaults.yaml
- ssf/files/default/formula/libtofs.jinja
- ssf/libtofs.jinja
* https://github.com/saltstack-formulas/template-formula/pull/187
* Additionally fixed a typo
> feat(libtofs): “files_switch” mess up the variable exported by “map.jinja”

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/telegraf-formula/pull/4
> feat(telegraf): adjust to new working matrix after `pytoml` changes

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/consul-formula/pull/48
> feat(formula): add `consul-formula`

- ssf/defaults.yaml
- ssf/formulas.yaml
* Already merged: https://github.com/saltstack-formulas/logrotate-formula/pull/52
> feat(logrotate): fix Kitchen to ensure `cron` installed on `Debian`

- ssf/defaults.yaml
- ssf/files/default/kitchen.yml
* `packages-formula`:
- https://github.com/saltstack-formulas/packages-formula/commit/a81f2dd4b337ebe2a898ed8ed91e585e5f19b254
* `systemd-formula`:
- Automated
> feat(kitchen): reinstall `udev` since removed from pre-salted images

- ssf/formulas.yaml
* https://github.com/saltstack-formulas/dhcpd-formula/pull/47
> feat(dhcpd): add `yaml_dump` state to Kitchen

- ssf/defaults.yaml
- ssf/formulas.yaml
* Include Fedora since also fixed
* Merge Rubocop into main lint job since violations resolved
> feat(dhcpd): adjust matrix to add `3000.1` & remove `2017.7`

- ssf/formulas.yaml
* https://github.com/saltstack-formulas/openldap-formula/pull/34
> feat(openldap): override `Metrics/BlockLength` cop

- .yamllint
- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_ssf-formula/.yamllint
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/node-formula/pull/48
> feat(formula): add `node-formula`

- ssf/config/formulas.sls
Just trying to get running with this again, and trying to resolve the issue where I want to run locally as a masterless minion.
- Do you think this is a suitable addition to `libsaltcli`? masterless is a type of `salt-call` so we could another variable to `libsaltcli` but I've decided to simplify things here and "overload" the `cli` variable. 
- Need to think through wether `ssf` would ever be run using non-masterless `salt-call` or `salt-ssh`.
Thoughts?
> fix: allow running as non-root

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* Attempted to get platforms working:
- Got `debian-10` & `opensuse-leap-15` working but with numerous
modifications to the formula
- Will leave this until PR queue has been cleared
> feat(formula): add `powerdns-formula` (without platforms)

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/tomcat-formula/pull/109
> feat(tomcat): update for `map.jinja` upgrade

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/lvm-formula/pull/20
> feat(lvm): finalise CI for fix PR 20

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://tree.taiga.io/project/myii-saltstack-formulas/task/173
* https://tree.taiga.io/project/myii-saltstack-formulas/task/174
* https://tree.taiga.io/project/myii-saltstack-formulas/task/175
* https://github.com/netmanagers/salt-image-builder/commit/9d66c100c9537800404f76f05514fd848a1e6bd6
> feat(arch-base): remove `master-py2-arch-base-latest`

- pillar.example
- ssf/defaults.yaml
- ssf/files/default/inspec/inspec.yml
- ssf/files/tofs_arvados-formula/.travis.yml
- ssf/files/tofs_arvados-formula/kitchen.yml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
Also:
```
feat(inspec.yml): adjust template to allow suite's `title` to be given
```
> feat(formula): add `arvados-formula` (forked into org)

- pillar.example
- ssf/config/formulas.sls
- ssf/defaults.yaml
- ssf/files/default/.travis.yml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/eclipse-formula/pull/29
* https://www.eclipse.org/downloads/packages/compare
Also includes:
```
feat(shellcheck): allow excluding paths (e.g. bash templates)
```
> feat(formula): add `eclipse-formula`

- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* Existing formulas
- `dhcpd`
- `nginx`
- `openldap`
- `php`
- `powerdns`
* Unconverted formula:
- `rundeck`
> feat(codeowners): add global owner for 5(+1) formulas

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/iscsi-formula/pull/35
> feat(iscsi): update & finalised based on PR 35

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/jetbrains-pycharm-formula/pull/8
> feat(formula): add `jetbrains-pycharm-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/jetbrains-intellij-formula/pull/29
> feat(formula): add `jetbrains-intellij-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/jetbrains-pycharm-formula/pull/4
> feat(formula): add `jetbrains-rubymine-formula`

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/mongodb-formula/pull/79
> feat(mongodb): introspect PR 79 (inc. adjust matrix to add `3000.2`)

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/jetbrains-datagrip-formula/pull/5
> feat(formula): add `jetbrains-datagrip-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/jetbrains-phpstorm-formula/pull/5
> feat(formula): add `jetbrains-phpstorm-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/jetbrains-resharper-formula/pull/2
> feat(formula): add `jetbrains-resharper-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/jetbrains-webstorm-formula/pull/6
> feat(formula): add `jetbrains-webstorm-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/jetbrains-goland-formula/pull/6
> feat(formula): add `jetbrains-goland-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/jetbrains-appcode-formula/pull/3
> feat(formula): add `jetbrains-appcode-formula`

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/systemd-formula/pull/57
> feat(systemd): update from PR 57

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/eclipse-formula/pull/32
> feat(eclipse): finalise PR 32

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/mongodb-formula/pull/83
> feat(mongodb): finalise PR 83

- ssf/defaults.yaml
- ssf/formulas.yaml
> feat(tomcat): use new platforms (`ubuntu-20.04` & `fedora-32`)

- ssf/defaults.yaml
- ssf/formulas.yaml
> feat(zabbix): use new platforms (`ubuntu-20.04` & `fedora-32`)

- ssf/defaults.yaml
- ssf/files/default/.travis.yml
- ssf/formulas.yaml
---
Also includes:
```
feat(ufw): use `bionic` (default) for Travis
```
> feat(ufw): use latest pre-salted images & add `without-ipv6` suite

- ssf/defaults.yaml
- ssf/files/default/kitchen.yml
- ssf/formulas.yaml
---
Also includes:
```
feat(deepsea): install `tar` & `gzip` in-formula instead
```
> feat(deepsea): use latest pre-salted images

- ssf/defaults.yaml
- ssf/formulas.yaml
> feat(mysql): use latest pre-salted images

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/jetbrains-clion-formula/pull/5
> feat(formula): add `jetbrains-clion-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/nut-formula/pull/5
> feat(formula): add `nut-formula`

- ssf/defaults.yaml
- ssf/formulas.yaml
> feat(packages): use latest pre-salted images

- ssf/defaults.yaml
- ssf/formulas.yaml
* Complete https://github.com/saltstack-formulas/iscsi-formula/pull/36
> feat(iscsi): use latest pre-salted images

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/maven-formula/pull/31
> feat(formula): add `maven-formula`

- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/golang-formula/pull/37
> feat(golang): finalise PR 37

- ssf/defaults.yaml
- ssf/formulas.yaml
* Fix https://github.com/saltstack-formulas/golang-formula/issues/41
> feat(golang): add `package` suite

- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/postfix-formula/pull/106#issuecomment-639668783
> feat(codeowners): add global owner (`postfix`)

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/java-formula/pull/10
> feat(formula): add `java-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/sqlplus-formula/pull/17
> feat(formula): add `sqlplus-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/sqldeveloper-formula/pull/24
> feat(formula): add `sqldeveloper-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_haproxy-formula/.salt-lint
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/haproxy-formula/pull/83
---
Replaces #77.
> feat(formula): add `haproxy-formula`

- ssf/defaults.yaml
- ssf/formulas.yaml
Includes:
* feat(defaults): update `saltimages` list after Sodium `3001` release
* feat(oracle): add InSpec `supports` node anchor including `oracle`
> feat(salt): adjust matrix to add Sodium `3001`

- pillar.example
- ssf/defaults.yaml
- ssf/formulas.yaml
* https://freenode.logbot.info/saltstack-formulas/20200620#c4173182
> feat(formula): add `suricata-formula`

- ssf/defaults.yaml
- ssf/files/tofs_salt-formula/Gemfile
- ssf/files/tofs_salt-formula/Gemfile.lock
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/salt-formula/pull/471
> feat(salt): add Windows testing

- ssf/config/formulas.sls
Up to now, there's been a slight issue with doing direct pushes to repos
when there are no changes to be pushed.  For example, we currently need
`libtofs.jinja` to be updated across formulas but not all of the
formulas have this file; when running across all formulas, this will
cause the temporary date-based branch to be created but then not
removed.  This commit is a quick fix for that, where the starting branch
is tracked and then checked out again at the end, before removing the
temporary branch (if it is still available).
> feat(formulas.sls): ensure temporary date-based branch is removed

- ssf/defaults.yaml
- ssf/formulas.yaml
* Extend https://github.com/saltstack-formulas/postgres-formula/pull/299
---
Already pushed the commit: https://github.com/saltstack-formulas/postgres-formula/commit/702323c24df1df6b11defd663b55cf38586bd3f3.
> feat(postgres): use latest pre-salted images

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/apache-formula/pull/280
> feat(apache): review PR 280

- ssf/defaults.yaml
- ssf/formulas.yaml
* Check https://github.com/saltstack-formulas/openssh-formula/pull/182
> feat(openssh): use latest pre-salted images

- ssf/formulas.yaml
* https://github.com/saltstack-formulas/openssh-formula/pull/185
> feat(openssh): review PR 185

- pillar.example
- ssf/config/formulas.sls
- ssf/defaults.yaml
- ssf/files/default/kitchen.yml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/proftpd-formula/pull/4
---
Also includes commit for allowing `run_options` to be supplied in `kitchen.yml`:
* https://github.com/saltstack-formulas/proftpd-formula/pull/4#discussion_r466882645
- [Extra command-line options to pass to `docker run` when starting the container](https://github.com/test-kitchen/kitchen-docker#run_options)
> feat(formula): add `proftpd-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/openntpd-formula/pull/6
> feat(formula): add `openntpd-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/rspamd-formula/pull/4
> feat(formula): add `rspamd-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/default/kitchen.yml
- ssf/files/tofs_devstack-formula/.salt-lint
- ssf/files/tofs_template-formula/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/devstack-formula/pull/46
> feat(formula): add `devstack-formula`

- ssf/defaults.yaml
- ssf/formulas.yaml
* Problems identified while reviewing:
- https://github.com/saltstack-formulas/template-formula/pull/203
> feat(template): fix `centos6` suite and rename to `upstart`

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/template-formula/pull/203
> feat(template): verify `map.jinja` using InSpec

- ssf/defaults.yaml
- ssf/files/default/inspec/README.md
- ssf/files/default/kitchen.yml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/openssh-formula/pull/187
* https://github.com/saltstack-formulas/openssh-formula/pull/189
* https://github.com/saltstack-formulas/openssh-formula/pull/192
* https://github.com/saltstack-formulas/openssh-formula/pull/195
Includes:
* feat(inspec): update `README` template for suite `share`
* feat(kitchen): manage `suite.driver` (e.g. for static `hostname`)
* https://github.com/saltstack-formulas/arvados-formula/commit/06050e0a5377d3d6a4c54c7f50fe53a06a07c837
* https://github.com/saltstack-formulas/openssh-formula/pull/195
> feat(openssh): verify `map.jinja` using InSpec

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/ufw-formula/pull/24
> feat(ufw): merge `rubocop` linter into main `lint` job

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_.github/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/lynis-formula/pull/5
> feat(formula): add `lynis-formula`

- pillar.example
- ssf/defaults.yaml
- ssf/files/tofs_.github/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/rng-tools-formula/issues/1
> feat(formula): add `rng-tools-formula`

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/nut-formula/pull/6
> feat(nut): add `mode-eq-none` suite & use Tiamat images

- ssf/defaults.yaml
- ssf/files/default/.travis.yml
- ssf/formulas.yaml
Also includes:
* feat(travis): add `pre-commit` for `template-formula`
> feat(template): use `platforms_new_inc_tiamat`

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/lynis-formula/pull/9
> feat(lynis): review PR 9

- ssf/config/formulas.sls
- ssf/defaults.yaml
- ssf/formulas.yaml
Pre-requisite for pushing changes across formulas using #259 (`pre-commit`).
> feat(formulas): capture recent changes across formulas

- commitlint.config.js
- ssf/defaults.yaml
- ssf/files/default/commitlint.config.js
* https://github.com/saltstack-formulas/template-formula/pull/208
---
CC: @dafyddj.
> feat(commitlint.config.js): add `{body,footer,header}-max(-line)-length`

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/arvados-formula/pull/7
> feat(arvados): add `dispatcher` suite

- ssf/defaults.yaml
- ssf/files/default/kitchen.yml
- ssf/formulas.yaml
Update to use latest `saltimages` pre-salted images.
> feat(openvpn): verify `map.jinja` using InSpec

- ssf/defaults.yaml
- ssf/formulas.yaml
Use `*platforms_new_saltimages` to use the newest images and to avoid
having to manage a list for `platforms`.
> feat(salt): adjust matrix to add Magnesium `3002`

- pillar.example
- ssf/config/formulas.sls
- ssf/defaults.yaml
- ssf/files/default/formula/_mapdata/_mapdata.jinja
- ssf/files/default/formula/_mapdata/init.sls
- ssf/files/default/inspec/README.md
- ssf/files/default/inspec/controls/_mapdata_spec.rb
- ssf/files/default/inspec/libraries/system.rb
- ssf/files/tofs_openntpd-formula/inspec/README.md
- ssf/files/tofs_sudoers-formula/inspec/README.md
- ssf/formulas.yaml
Manage across these formulas:
* `openntpd` (#244)
* `openssh` (#251)
* `openvpn` (#271)
* `sudoers` (#245)
* `template` (#249)
> feat(_mapdata): manage `map.jinja` verification

- ssf/defaults.yaml
- ssf/files/default/formula/_mapdata/init.sls
- ssf/formulas.yaml
* Prompted by https://github.com/saltstack-formulas/rabbitmq-formula/pull/61
> feat(rabbitmq): manage `map.jinja` verification

- .pre-commit-config.yaml
- ssf/defaults.yaml
- ssf/files/default/.pre-commit-config.yaml
* https://freenode.logbot.info/saltstack-formulas/20210201#c6748575-c6748847
> feat(pre-commit): update hook for `rubocop`

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/packages-formula/pull/72
> feat(packages): review PR 72

- ssf/defaults.yaml
- ssf/files/default/.pre-commit-config.yaml
* https://github.com/saltstack-formulas/template-formula/pull/228
> feat(template): review PR 228

- ssf/formulas.yaml
* https://github.com/saltstack-formulas/template-formula/pull/225
> feat(template): review PR 225

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/nginx-formula/pull/269
---
Adding to CI based upon:
* https://gitlab.com/javierbertoli/nginx-formula/-/pipelines/271945785
> feat(nginx): review PR 269 (also add CI for `passenger` suite)

- ssf/defaults.yaml
- ssf/files/default/Gemfile
- ssf/files/tofs_php-formula/Gemfile.lock
- ssf/formulas.yaml
Finalise PR:
* https://github.com/saltstack-formulas/php-formula/pull/218
> feat(php): add FreeBSD testing (Vagrant)

- ssf/defaults.yaml
- ssf/files/default/Gemfile
- ssf/files/tofs_golang-formula/Gemfile.lock
- ssf/formulas.yaml
Finalise PR:
* https://github.com/saltstack-formulas/golang-formula/pull/45
> feat(golang): add FreeBSD, OpenBSD & Windows testing (Vagrant)

- ssf/defaults.yaml
- ssf/files/default/Gemfile
- ssf/files/default/kitchen.vagrant.yml
- ssf/formulas.yaml
Pre-salted Vagrant boxes:
* https://app.vagrantup.com/myii/boxes/freebsd-12.2-master-py3
* https://app.vagrantup.com/myii/boxes/freebsd-11.4-master-py3
* https://app.vagrantup.com/myii/boxes/freebsd-12.2-3002.6-py3
* https://app.vagrantup.com/myii/boxes/freebsd-11.4-3002.6-py3
* https://app.vagrantup.com/myii/boxes/openbsd-6.8-3001.1-py3
> feat(vagrant): use pre-salted boxes & conditional local settings

- ssf/defaults.yaml
- ssf/files/default/kitchen.vagrant.yml
* https://app.vagrantup.com/techneg/boxes/win10x64-pro-salt
> feat(vagrant): add Windows 10 pre-salted box

- ssf/defaults.yaml
- ssf/files/default/formula/_mapdata/init.sls
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/cert-formula/pull/36
* https://github.com/saltstack-formulas/cert-formula/pull/37
> feat(cert): review PRs 36 & 37

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/zabbix-formula/pull/146
> feat(zabbix): review PR 146

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/rabbitmq-formula/pull/66
> feat(rabbitmq): review PR 66

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/cert-formula/pull/40
> feat(cert): review & finalise PR 40

- ssf/formulas.yaml
* https://github.com/saltstack-formulas/nginx-formula/pull/278
> feat(nginx): review PR 278

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/94
> feat(salt): update Fedora testing after `3003` release

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://app.vagrantup.com/myii/boxes/openbsd-6.9-3002.6-py3
> feat(vagrant): add OpenBSD 6.9 testing across formulas

- ssf/formulas.yaml
* https://github.com/saltstack-formulas/salt-formula/pull/506
> feat(salt): review PR 506

- ssf/formulas.yaml
* https://github.com/saltstack-formulas/rng-tools-formula/pull/4
> feat(rng-tools): review PR 4

- ssf/formulas.yaml
> feat(ntp): add helper state to run service in containers

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/letsencrypt-formula/pull/83
> feat(letsencrypt): review PR 83

- ssf/defaults.yaml
- ssf/formulas.yaml
Failing for the first time in the weekly tests:
* https://gitlab.com/myii/java-formula/-/jobs/1400836673
* https://gitlab.com/myii/java-formula/-/jobs/1400836667
> feat(java): disable failing suite in CI

- ssf/formulas.yaml
* https://github.com/saltstack-formulas/logrotate-formula/pull/58
> feat(logrotate): review PR 58

- .yamllint
- ssf/defaults.yaml
- ssf/files/default/.yamllint
- ssf/files/tofs_rabbitmq-formula/.salt-lint
* https://github.com/saltstack-formulas/rabbitmq-formula/pull/84
> feat(rabbitmq): review PR 84 (inc. `yamllint` update)

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/rabbitmq-formula/pull/89
Widen the CI setup to run as many platforms as possible across both suites.
> feat(rabbitmq): review PR 89

- ssf/files/default/.gitlab-ci.yml
* https://github.com/saltstack-formulas/template-formula/pull/237
> feat(template): review PR 237

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/sudoers-formula/pull/78
> feat(sudoers): review PR 78

- Gemfile.lock
- ssf/defaults.yaml
- ssf/files/default/Gemfile.lock
- ssf/files/tofs_openssh-formula/Gemfile.lock
- ssf/files/tofs_openvpn-formula/Gemfile.lock
Already pushed to one formula before starting this PR:
* https://github.com/saltstack-formulas/aegir-formula/commit/4d2345cfa1d439aeed967262851f4ef3e4a52f7b
> feat(gemfile.lock): use `bundle update` to get latest gems [2021-W35]

- ssf/formulas.yaml
* https://github.com/saltstack-formulas/mysql-formula/pull/262
> feat(mysql): review PR 262

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/docker-formula/pull/287
* https://github.com/saltstack-formulas/docker-formula/pull/300
> feat(docker): review PRs 287 & 300

- ssf/config/formulas.sls
Add layer of protection to process of modifying files, to avoid unwanted
changes.
References:
* https://stackoverflow.com/questions/24520791/check-if-git-stash-stashed-anything
Alternative using Salt (for potential future use):
```
salt * git.stash .../test-formula push opts='-m "test this message"'
```
> feat(formulas): use `git stash` before making changes to formulas

- pillar.example
- ssf/config/formulas.sls
- ssf/defaults.yaml
- ssf/files/default/kitchen.yml
- ssf/files/default/test/salt/pillar/top.sls
- ssf/formulas.yaml
New functionality to manage when reviewing this PR:
* https://github.com/saltstack-formulas/template-formula/pull/238
> feat: use `pillars_from_directories` & `test/salt/pillar/top.sls`

- ssf/defaults.yaml
- ssf/files/default/.github/workflows/kitchen.windows.yml
- ssf/formulas.yaml
So the failing line `Set-WSManInstance -ResourceURI winrm/config/service -ValueSet @{AllowUnencrypted="true"}` isn't actually necessary anyway...
> feat(proxy): fix setting up WinRM

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack/kitchen-salt/pull/340
> feat(windows): use Salt version `3004` (as `latest`) after `kitchen-salt` fix

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/cron-formula/pull/15#issuecomment-1013006328
> feat(cron): add Gentoo support

- pillar.example
- ssf/defaults.yaml
- ssf/files/default/Gemfile
- ssf/files/default/docs/CONTRIBUTING.rst
- ssf/files/tofs_snmp-formula/Gemfile.lock
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/snmp-formula/pull/43#issuecomment-1012833124
> feat(formula): add `snmp-formula`

- ssf/defaults.yaml
- ssf/files/default/pre-commit_semantic-release.sh
* https://github.com/miyakogi/m2r/issues/66#issuecomment-988733957
* https://github.com/CrossNox/m2r2
* https://pypi.org/project/m2r2/
> feat(pre-commit_semantic-release.sh): replace broken `m2r` with `m2r2`

- Gemfile
- ssf/defaults.yaml
- ssf/files/default/Gemfile
* https://github.com/saltstack-formulas/template-formula/pull/241
> feat(gemfile): allow rubygems proxy to be provided as an env var

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/137
> feat(saltimages): update with latest changes from `salt-image-builder`

- ssf/defaults.yaml
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/docker-formula/pull/312
> feat(docker): review PR 312

- .pre-commit-config.yaml
- .rubocop.yml
- ssf/defaults.yaml
- ssf/files/default/.gitlab-ci.yml
- ssf/files/default/.pre-commit-config.yaml
- ssf/files/default/.rubocop.yml
- ssf/formulas.yaml
Tested across formulas and already prepared all necessary fixes (to be
pushed out once this update has been):
* https://saltstack-formulas.zulipchat.com/#narrow/stream/239693-CI/topic/myii-ci.2F2022-W06c
> feat(formulas): update linters to latest versions

- pillar.example
- ssf/defaults.yaml
- ssf/files/default/Gemfile
- ssf/files/default/docs/CONTRIBUTING.rst
- ssf/files/tofs_dnsmasq-formula/Gemfile.lock
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/dnsmasq-formula/pull/25
- Original PR
* https://github.com/saltstack-formulas/dnsmasq-formula/pull/27
- Replacement PR, when unable to push to the original PR's branch
> feat(formula): add `dnsmasq-formula`

- ssf/defaults.yaml
- ssf/files/default/Gemfile
- ssf/files/tofs_vault-formula/.salt-lint
- ssf/files/tofs_vault-formula/Gemfile.lock
- ssf/formulas.yaml
Rescue abandoned PR:
* https://github.com/saltstack-formulas/vault-formula/pull/32
> feat(vault): add FreeBSD testing (Vagrant)

- ssf/formulas.yaml
* https://github.com/saltstack-formulas/consul-formula/pull/56
> feat(consul): review PR 56

- ssf/formulas.yaml
* https://github.com/saltstack-formulas/consul-formula/pull/55
> feat(consul): review PR 55 (v5 `map.jinja`)

- ssf/formulas.yaml
* https://github.com/saltstack-formulas/consul-formula/pull/58
> feat(consul): review PR 58

- ssf/files/default/Gemfile
- ssf/files/tofs_consul-formula/Gemfile.lock
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/consul-formula/pull/59
> feat(consul): review PR 59

- ssf/files/default/.gitlab-ci.yml
* https://github.com/saltstack-formulas/template-formula/pull/249
> feat(template): review PR 249

- ssf/defaults.yaml
- ssf/files/default/kitchen.vagrant.yml
Recommended doing so by @dafyddj.
> feat(vagrant): use `linked_clone` at all times (inc. CI)

- ssf/formulas.yaml
* https://github.com/saltstack-formulas/collectd-formula/pull/157
> feat(collectd): review PR 157

- pillar.example
- ssf/defaults.yaml
- ssf/files/default/docs/CONTRIBUTING.rst
- ssf/formulas.yaml
* https://github.com/saltstack-formulas/carbon-relay-ng-formula/pull/5
> feat(formula): add `carbon-relay-ng-formula`
